# Generated by Django 6.0.6 on 2026-07-11 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo_electronico', models.EmailField(max_length=150, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('password_hash', models.CharField(max_length=256)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuarios_taskflow',
            },
        ),
        migrations.AlterField(
            model_name='tarea',
            name='asignada_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.usuario'),
        ),
    ]
